
services:
  ws_publicos_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: apec-ws-publicos-api-standard
    
    # Mapea el puerto 80 del host al puerto interno 9880 del contenedor
    ports:
      - "9880:9880"
      
    # Volumen persistente para la base de datos (SQLite)
   ## volumes:
    ##  - ./output:/app 
      
    restart: always